version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: notes-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: notes-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: notes-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: